#! /bin/bash

wipefs -a /dev/sda
parted -s -a optimal /dev/sda mklabel gpt
parted -s -a optimal /dev/sda unit mib
parted -s -a optimal /dev/sda mkpart primary 1 3
parted -s -a optimal /dev/sda name 1 grub
parted -s -a optimal /dev/sda set 1 bios_grub on
parted -s -a optimal /dev/sda mkpart primary 3 131
parted -s -a optimal /dev/sda name 2 boot
parted -s -a optimal /dev/sda mkpart primary 131 643
parted -s -a optimal /dev/sda name 3 swap
parted -s -a optimal /dev/sda mkpart primary 643 -- -1
parted -s -a optimal /dev/sda name 4 rootfs
parted -s -a optimal /dev/sda set 2 boot on

mkfs.ext2 -F /dev/sda2
mkfs.ext4 -F /dev/sda4
mkswap /dev/sda3
swapon /dev/sda3

mount /dev/sda4 /mnt/gentoo

ntpd -q -g

cd /mnt/gentoo

wget https://gentoo.osuosl.org/releases/amd64/autobuilds/latest-stage3.txt
CURRENT_STAGE3=`cat latest-stage3.txt | cut -d'/' -f2 | cut -d' ' -f1 | grep -v '#' | sed -n 1p`
wget https://gentoo.osuosl.org/releases/amd64/autobuilds/current-stage3-amd64/$CURRENT_STAGE3
tar xvf stage3-*.tar.xz --xattrs-include='*.*' --numeric-owner
rm latest-stage3.txt

sed -i 's/COMMON_FLAGS=.*/COMMON_FLAGS="-O2 -march=native -pipe"/' /mnt/gentoo/etc/portage/make.conf 
PHYSICAL_CORES=$(( $(lscpu | awk '/^Socket/{ print $2 }') * $(lscpu | awk '/^Core/{ print $4 }') +1))
echo MAKEOPTS=\"-j$PHYSICAL_CORES\" >> /mnt/gentoo/etc/portage/make.conf

echo 'GENTOO_MIRRORS="http://www.gtlib.gatech.edu/pub/gentoo https://gentoo.osuosl.org/"' >> /mnt/gentoo/etc/portage/make.conf

mkdir --parents /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf

cp --dereference /etc/resolv.conf /mnt/gentoo/etc/

mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev

mkdir /mnt/gentoo/etc/petrichor_setup
cp /etc/petrichor_setup/petrichor-setup-chroot.sh /mnt/gentoo/etc/petrichor_setup/. 
cp /etc/petrichor_setup/petrichor.linux.config /mnt/gentoo/etc/petrichor_setup/.
cp /etc/petrichor_setup/petrichor.linux.fstab /mnt/gentoo/etc/petrichor_setup/.

chmod +x /mnt/gentoo/etc/petrichor_setup/petrichor-setup-chroot.sh
chroot /mnt/gentoo /etc/petrichor_setup/petrichor-setup-chroot.sh

cd
umount -l /mnt/gentoo/dev{/shm,/pts,}
umount -R /mnt/gentoo
reboot
